---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: molecule-ingress
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/health-probe-path: "/_admin/status"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "appGatewaySslCert"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: molecule-service
            port:
              number: 9090
              
