---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: molecule-keda-hpa
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          StatefulSet
    name:          molecule
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 3
  maxReplicaCount: 200
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
