apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  labels:
    app: molecule
spec:
  selector:
    app: molecule
  ports:
  - name: port1
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: port2
    protocol: TCP
    port: 9093
    targetPort: 9090
