apiVersion: v1
kind: Service
metadata:
  name: molecule-service
  labels:
    app: molecule
spec:
  selector:
    type: NodePort
    app: molecule
  ports:
  - name: https
    protocol: TCP
    port: 9093
    targetPort: 9090
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
